# Homework 2
## Student Name: 盧允凡
## Student ID: 107065507
***
# Dynamics Programming
### 1. Longest Common Subsequence
### 2. Matrix Chain Multiplication
### 3. Text Justification
### 4. Coin Change
***
### For each problem, I employed three different approaches.
* **Straight forward brute-force Approach (recursion)**
>This method is to find a recurrence relation to solve the problem.
* **Dictinary-based Approach**
>Same as the first approach, but store the answers in a dictionary, which is a data type of Python, so we don't  have to compute the repeated subproblems. This approach is also known as "Top-down DP".
* **Array-based Approach**
>based on the recurrence relation, construct a table, and find appropriate way to fill the answers of subproblems into the table and find the optimal answer.

# 1. Longest Common Subsequence
***
## <font color="blue">Input</font>: two sequences x and y
## <font color="blue">Output</font>: the length of the longest common subsequence
***
## <font color="blue">Sample Input</font>: lcs('NTHU', 'NCTU')
## <font color="blue">Sample Output</font>: 3
***
## brute-force

In [13]:
# recursion approach (brute-force)

def lcs(x, y):
    if len(x)==0 or len(y)==0:
        return 0
    if x[0] == y[0]:
        print (x[0])
        ans = 1 + lcs(x[1:], y[1:])
    else:
        ans = max(lcs(x, y[1:]), lcs(x[1:], y))
    return ans

lcs("NTHU", "NCTU")

N
T
U
U
U
U


3

## Dictinary-based

In [14]:
# Dictinary-based Approach

def lcsDict(x, y, dic):
    key = str(len(x)) + "-" + str(len(y))
    if key in dic:
        return dic[key]
    if len(x) == 0 or len(y) == 0:
        dic[key] = 0
        return dic[key]
    if x[0] == y[0]:
        print(x[0])
        ans = 1 + lcsDict(x[1:], y[1:], dic)
    else:
        ans = max(lcsDict(x, y[1:], dic), lcsDict(x[1:], y, dic))
    dic[key] = ans
    return dic[key]

lcsDict('NTHU', 'NCTU', {})

N
T
U


3

## Array-based

In [1]:
# Array-based Approach
# 1D array

def lcsLoop(x, y):
    arr = [[0 for j in range(len(y)+1)] for i in range(len(x)+1)]
    for i in range(1, len(x)+1):
        for j in range(1, len(y)+1):
            if x[len(x)-i] == y[len(y)-j]:
                arr[i][j] = 1 + arr[i-1][j-1]
            else:
                arr[i][j] = max(arr[i-1][j], arr[i][j-1])
    print (arr)
    
    return arr[len(x)][len(y)]

lcsLoop('NTHU', 'NCTU')

[[0, 0, 0, 0, 0], [0, 1, 1, 1, 1], [0, 1, 1, 1, 1], [0, 1, 2, 2, 2], [0, 1, 2, 2, 3]]


3

# 2. Matrix Chain Multiplication
***
## <font color="blue">Input</font>: a list of matrices to multiply; an m by n matrix is represented by (m, n) 
## <font color="blue">Output</font>: the minium times of multiplication
***
## <font color="blue">Sample Input</font>: [(1, 10), (10, 1), (1, 5)]
## <font color="blue">Sample Output</font>: 15
***
## brute force

In [2]:
# recursion approach (brute-force)

def mcm(ch):
    if len(ch) <= 1:
        return 0
    else:
        cost = min([ mcm(ch[:k])+
                   mcm(ch[k:]) +
                   ch[0][0] * ch[k-1][1] * ch[-1][1]
                   for k in range(1, len(ch)) ])
        return cost
    
chain = [(10, 11), (11, 25), (25, 40), (40, 2)]
mcm(chain)

2770

## Dictinary-based
## Here, we need to input two more parameters in mcmDict(ch, i, j, dic) to indicate where to start and end in the list of matrices. i.e., the minimum multiplication from m[i] to m[j].

In [3]:
# Dictinary-based Approach

def mcmDict(ch, i, j, dic):
    key = str(i) + "-" + str(j)
    
    if key in dic:
        return dic[key]
    else:
        if i == j:
            dic[key] = 0
        else:
            dic[key] = min([ mcmDict(ch, i, k, dic)+
                           mcmDict(ch, k+1, j, dic) +
                           ch[i][0] * ch[k][1] * ch[j][1]
                           for k in range(i, j) ])
        return dic[key]
    
mcmDict(chain, 0, len(chain)-1, {})

2770

## Array-based
## Here, we fill the table from left-up to right-down.

In [5]:
# Array-based Approach
# 2D table

import numpy as np

def mcmLoop(chain):
    n = len(chain)
    table = np.zeros((n, n), dtype=int)
    
    for i in range(n-1):              # fill from left-up to right-down
        r, c = 0, i+1
        for j in range(n-1-i):        # ch[i,j] = min{ch[i,k] + ch[k+1,j] + pi-1*pk*pj} for i<=k<j
            table[r, c] = min([ table[r, k] + 
                            table[k+1, c] +
                            chain[r][0] * chain[k][1] * chain[c][1]
                            for k in range(r, c) ])
            r, c = r+1, c+1
    print(table)
    return table[0][n-1]

mcmLoop(chain)

[[    0  2750 12750  2770]
 [    0     0 11000  2550]
 [    0     0     0  2000]
 [    0     0     0     0]]


2770

# 3. Text Justification
***
## <font color="blue">Input</font>: a list of paragraph that splited in words 
## <font color="blue">Output</font>: the minium cost to waste
***
## brute force

In [21]:
# brute-force

def costFunction(usage, lw):
    return (lw - usage)**2

def tj(tl, lw):        # assume that lw is always larger than t1
    if len(tl) == 0:
        return 0
    
    elif len(tl) == 1:
        return costFunction(len(tl[0]), lw)
    
    else:
        usage = len(tl[0])                     # we can always put the first word for usage since lw >= t1
        waste = [costFunction(usage, lw)]      # an array to record the waste from 1 to n words in line
        maxwords = 1
        while (usage+1+len(tl[maxwords]) <= lw):    # +1 means the 'space'
            usage = usage + 1 + len(tl[maxwords])
            waste.append(costFunction(usage, lw))
            maxwords += 1
            if maxwords == len(tl):
                break
                
    min_cost = min([ waste[k] + tj(tl[k+1:], lw) for k in range(maxwords) ])
                
    return min_cost

text = "It was the worst of time. It was the best of time.".split()
tj(text, 30)

61

## Dictinary-based

In [22]:
# Dictinary-based Approach

def tjDict(tl, lw, dic, i, j):    # from tl[i] to tl[j]
    
    key = str(i) + "-" + str(j)
    
    if key in dic:
        return dic[key]
    
    elif i >= j:
        dic[key] = 0
        return dic[key]
    
    else:
        usage = len(tl[i])
        waste = [costFunction(usage, lw)]
        k = 1
        while (i+k<j and usage+1+len(tl[i+k]) <= lw):
            usage = usage + 1 + len(tl[i+k])
            waste.append(costFunction(usage, lw))
            k += 1
            
        dic[key] = min([ w + tjDict(tl, lw, dic, i+r+1, j) for r, w in enumerate(waste) ])
        return dic[key]
    
tjDict(text, 30, {}, 0, len(text))

61

## Array-based

In [23]:
# Array-based Approach
# 1D array

def tjLoop(tl, lw):
    t_len = len(tl)
    cost = [0]*(t_len+1)
    wordsinline = [0]*(t_len+1)
    
    for i in range(t_len-1, -1, -1):        # from n to 0
        usage = len(tl[i])
        waste = [costFunction(len(tl[i]), lw)]
        j = i + 1
        while (j <= t_len-1 and usage+1+len(tl[j]) <= lw):
            usage = usage+1+len(tl[j])
            waste.append(costFunction(usage, lw))
            j += 1
            
        cost[i], wordsinline[i] = min([ (w + cost[i+1+k], k+1) for k, w in enumerate(waste) ])    # k = words in line
        
    print ("Cost", cost)
    print ("Wordsinline", wordsinline)
    
    jtext = ""
    i = 0
    while i <= t_len-1:
        line = str(tl[i])
        if i < t_len-1:
            for j in range(i+1, i+wordsinline[i]):
                line += " " + str(tl[j])
        line += "\n"
        jtext += line
        i += wordsinline[i]
        
    print (jtext)
    
tjLoop(text, 30)

Cost [61, 100, 162, 250, 394, 0, 36, 81, 169, 289, 484, 625, 0]
Wordsinline [6, 5, 5, 4, 4, 7, 6, 5, 4, 3, 2, 1, 0]
It was the worst of time.
It was the best of time.



# 4. Coin Change
***
## <font color="blue">Input</font>: a list of coins that can be used and a value N
## <font color="blue">Output</font>: how many ways to make the change
***
## <font color="blue">Sample Input</font>: [2, 5, 3, 6]
## <font color="blue">Sample Output</font>: 10
***
## brute force

In [24]:
# brute-force

def coinChange(coin, N):
    if N == 0:
        return 1
    elif N < 0:
        return 0
    elif N>0 and len(coin)<=0:
        return 0
    else:
        return coinChange(coin[:-1], N) + coinChange(coin, N-coin[-1])

c = [2,5,3,6]
coinChange(c, 10)

5

## Dictinary-based
## we need a number M that means from coin[0] to coin[M] are available.

In [6]:
# Dictinary-based Approach

def ccDict(coin, M, N, dic):
    key = str(M) + "-" + str(N)
    if key in dic:
        return dic[key]
    else:
        if N == 0:
            dic[key] = 1
        elif N < 0:
            dic[key] = 0
        elif N>0 and M<=0:
            dic[key] = 0
        else:
            dic[key] = ccDict(coin, M-1, N, dic) + ccDict(coin, M, N-coin[M-1], dic)
            
        return dic[key]
            
c = [2,5,3,6]
ccDict(c, len(c), 10, {})

5

## Array-based

In [3]:
# Array-based Approach
# 2D array

def ccLoop(coin, N):
    M = len(coin)
    table = [[0 for x in range(M)] for x in range(N+1)] 
    
    for i in range(M): 
        table[0][i] = 1
        
    for i in range(1, N+1):    # row-major
        for j in range(M):
            t1 = table[i][j-1] if j >= 1 else 0
            t2 = table[i - coin[j]][j] if i-coin[j] >= 0 else 0
            table[i][j] = t1 + t2 
    
    print(table)
    return table[N][M-1]
    
c = [2,5,3,6]
ccLoop(c, 10)

[[1, 1, 1, 1], [0, 0, 0, 0], [1, 1, 1, 1], [0, 0, 1, 1], [1, 1, 1, 1], [0, 1, 2, 2], [1, 1, 2, 3], [0, 1, 2, 2], [1, 1, 3, 4], [0, 1, 3, 4], [1, 2, 4, 5]]


5